import {useEffect,useState} from 'react';
import {ArrowUpRight,Bell,Check,Clock3,Pause,Play,Plus,RefreshCw,Settings2,ShieldCheck} from 'lucide-react';
import {request} from '../api/client';
import {dateTime,type OperationsData,type PilotConfig} from '../api/operations';
import {Dialog,Notice,Status} from './common';
import {Button} from './ui/button';
import TargetSetup from './TargetSetup';

export default function Monitoring({view,navigate}:{view:'monitoring'|'inbox';navigate:(path:string)=>void}){
 const [data,setData]=useState<OperationsData|null>(null),[error,setError]=useState(''),[busy,setBusy]=useState(''),[feedback,setFeedback]=useState('');
 const [setup,setSetup]=useState(false),[initial,setInitial]=useState<PilotConfig|undefined>();
 const [retention,setRetention]=useState<{jobs:string[];notices:string[];confirmation:string;notice:string}|null>(null);
 const [refresh,setRefresh]=useState(0),[fetchError,setFetchError]=useState('');
 useEffect(()=>{const controller=new AbortController();let live=true,inflight=false;
  async function load(){if(inflight)return;inflight=true;try{const result=await request<OperationsData>('/api/v1/operations',controller.signal);if(live){setData(result);setFetchError('');}}catch(e){if(live&&(e as Error).name!=='AbortError')setFetchError((e as Error).message);}finally{inflight=false;}}
  void load();const timer=setInterval(()=>{if(document.visibilityState==='visible')void load();},10000);
  return ()=>{live=false;controller.abort();clearInterval(timer);};
 },[refresh]);
 async function action(id:string,value:string){setBusy(id);setError('');setFeedback('');try{await request('/api/v1/targets/'+id+'/actions',undefined,{action:value});setFeedback(value==='PAUSE'?'Monitoring paused; active work is being cancelled.':value==='RUN_ONCE'?'Observation queued. Its result will appear in recorded assessments.':value==='CANCEL'?'Cancellation requested.':'Cadence enabled while the authorized runner is active.');setRefresh(x=>x+1);}catch(e){setError((e as Error).message);}finally{setBusy('');}}
 async function edit(id:string){setBusy(id);try{setInitial(await request<PilotConfig>('/api/v1/targets/'+id));setSetup(true);}catch(e){setError((e as Error).message);}finally{setBusy('');}}
 async function markRead(id:string){setBusy(id);try{await request('/api/v1/notifications/'+id+'/read',undefined,{});setRefresh(x=>x+1);}catch(e){setError((e as Error).message);}finally{setBusy('');}}
 async function previewRetention(){try{setRetention(await request('/api/v1/operations/retention'));}catch(e){setError((e as Error).message);}}
 async function applyRetention(){if(!retention)return;setBusy('retention');try{await request('/api/v1/operations/retention',undefined,{confirmation:retention.confirmation});setRetention(null);setFeedback('Reviewed operational metadata removed. Evidence and review history were retained.');setRefresh(x=>x+1);}catch(e){setError((e as Error).message);}finally{setBusy('');}}
 return <section aria-label={view==='monitoring'?'Local monitoring':'Notification inbox'}>
 <div className="section-heading"><div><h2>{view==='monitoring'?'Keep the next visit in view.':'Your review inbox.'}</h2><p className="muted">{view==='monitoring'?'Explicit scope. A visible cadence. Evidence you can return to.':'Local notifications link differences and collection limits to their evidence.'}</p></div><div className="button-group"><Button variant="outline" onClick={()=>setRefresh(x=>x+1)}><RefreshCw size={16}/>Refresh</Button>{view==='monitoring'&&<Button disabled={data?.demo||!data} onClick={()=>{setInitial(undefined);setSetup(true);}}><Plus size={16}/>Set up store</Button>}</div></div>
 {(error||fetchError)&&<Notice title="Action unavailable" tone="danger"><p>{error||fetchError}</p><Button variant="outline" onClick={()=>setRefresh(x=>x+1)}>Retry status</Button></Notice>}
 {feedback&&<p className="feedback" role="status"><Check size={16}/>{feedback}</p>}
 {!data&&!error&&<div className="state-message" role="status">Reading local monitoring state…</div>}
 {data?.demo&&<Notice title="Synthetic demo · read only"><p>Monitoring and review writes are unavailable in this dataset.</p></Notice>}
 {data&&view==='monitoring'&&<>
 <div className="runner-band"><ShieldCheck size={22}/><div><strong>Local runner</strong><p>{data.worker.status==='READY'?'Ready for explicitly authorized observations.':'Collection requires a separately authorized pilot runtime session.'}</p></div><Status value={data.worker.status}/></div><p className="muted"><a href="/setup-guide.html" target="_blank" rel="noreferrer">Open the local setup guide</a> · Explicit preparation and recovery steps</p>
 {data.worker.code&&<Notice title="Runner needs attention"><p>{data.worker.code.replaceAll('_',' ')}. Follow the pilot recovery guide before restarting.</p></Notice>}
 {!data.targets.length?<div className="onboarding-card"><span className="large-icon"><Clock3 size={30}/></span><h2>Your first monitored journey starts here.</h2><p>Define a store, the public pages you are authorized to observe, and a short grant. Capture an initial visit, then select a baseline after reviewing its coverage.</p><ol><li>Declare the store and observation journey</li><li>Run an authorized visit and review the baseline</li><li>Compare later visits and record your decision</li></ol><Button disabled={data.demo} onClick={()=>{setInitial(undefined);setSetup(true);}}>Configure a store<ArrowUpRight size={16}/></Button></div>:
 <div className="target-grid">{data.targets.map(target=>{const expired=new Date(target.grant_expires_at).getTime()<=Date.now(),active=target.last_job&&['QUEUED','RUNNING'].includes(target.last_job.status);return <article className="target-card" key={target.id}><div className="section-heading"><div><span className="eyebrow">{target.id} · v{target.version}</span><h3>{target.label}</h3></div><Status value={expired?'GRANT_EXPIRED':target.state}/></div><code>{target.origin}</code><dl className="metadata-grid"><div><dt>Cadence</dt><dd>Every {target.cadence_minutes} minutes</dd></div><div><dt>Next visit</dt><dd>{dateTime(target.next_at)}</dd></div><div><dt>Grant expires</dt><dd>{dateTime(target.grant_expires_at)}</dd></div><div><dt>Comparison reference</dt><dd>{target.baseline_id?'Baseline selected':'Choose after first visit'}</dd></div></dl>
 {target.last_job&&<div className="last-job"><Status value={target.last_job.status}/><span>{dateTime(target.last_job.ended_at||target.last_job.queued_at)}</span>{target.last_job.code&&<p>{target.last_job.code.replaceAll('_',' ')}</p>}{['COMPLETED','PARTIAL'].includes(target.last_job.status)&&<Button variant="ghost" onClick={()=>navigate('/runs/'+target.last_job!.run_id+'/journey')}>Inspect latest visit<ArrowUpRight size={14}/></Button>}</div>}
 <div className="button-group"><Button variant="outline" disabled={!!busy||expired||data.worker.status!=='READY'||!!active} onClick={()=>action(target.id,'RUN_ONCE')}><Play size={15}/>Run once</Button>{target.state==='ACTIVE'?<Button variant="outline" disabled={!!busy} onClick={()=>action(target.id,'PAUSE')}><Pause size={15}/>Pause</Button>:<Button variant="outline" disabled={!!busy||expired||data.worker.status!=='READY'} onClick={()=>action(target.id,'START')}><Clock3 size={15}/>Start cadence</Button>}{active&&<Button variant="ghost" disabled={!!busy} onClick={()=>action(target.id,'CANCEL')}>Cancel visit</Button>}<Button variant="ghost" disabled={!!busy||target.state!=='PAUSED'||!!active} onClick={()=>edit(target.id)}><Settings2 size={15}/>Edit / renew</Button></div></article>;})}</div>}
 <details className="surface"><summary>Recent jobs and operational retention</summary><p className="muted">Latest 50 jobs. Unread alerts remain in the inbox. Raw evidence is retained separately; review-linked evidence cannot be deleted.</p><ul className="job-list">{data.jobs.map(j=><li key={j.id}><code>{j.target_id} · {j.id.slice(0,8)}</code><Status value={j.status}/><span>{dateTime(j.queued_at)}</span>{j.code&&<span>{j.code.replaceAll('_',' ')}</span>}</li>)}</ul><Button variant="outline" disabled={data.demo} onClick={previewRetention}>Review history cleanup</Button></details>
 </>}
 {data&&view==='inbox'&&<><div className="inbox-heading"><Bell size={18}/><strong>{data.unread} unread</strong><span>Showing up to 100 items · unread first</span></div>{!data.notices.length?<div className="onboarding-card"><Bell size={30}/><h2>Nothing needs review yet.</h2><p>After an authorized observation, differences, partial coverage and failures appear here. This inbox sends no email or external messages.</p><Button variant="outline" onClick={()=>navigate('/assessments?view=monitoring')}>View monitoring</Button></div>:<div className="inbox-list">{data.notices.map(n=><article key={n.id} className={'inbox-item '+(n.read_at?'read':'unread')}><div className="section-heading"><Status value={n.kind}/><time>{dateTime(n.last_at)}</time></div><h3>{n.message}</h3><p className="muted">{n.target_id} · {n.repeats>1?n.repeats+' matching observations grouped':'Local inbox delivery recorded'}</p><div className="button-group">{n.baseline_id&&n.candidate_id?<Button onClick={()=>navigate('/changes?baseline='+n.baseline_id+'&candidate='+n.candidate_id)}>Review comparison<ArrowUpRight size={16}/></Button>:n.candidate_id&&<Button variant="outline" onClick={()=>navigate('/runs/'+n.candidate_id+'/journey')}>Inspect observation</Button>}{!n.read_at&&<Button variant="ghost" disabled={!!busy} onClick={()=>markRead(n.id)}><Check size={16}/>Mark read</Button>}</div></article>)}</div>}</>}
 <Dialog open={setup} onClose={()=>{if(!busy)setSetup(false);}} title={initial?'Edit scope / renew authorization':'Set up an authorized store'}>{setup&&<TargetSetup initial={initial} onBusyChange={value=>setBusy(value?'setup':'')} onCancel={()=>setSetup(false)} onSaved={()=>{setSetup(false);setFeedback('Target saved paused. Review its scope before starting collection.');setRefresh(x=>x+1);}}/>}</Dialog>
 <Dialog open={!!retention} onClose={()=>{if(!busy)setRetention(null);}} title="Review operational cleanup"><p>{retention?.notice}</p><p>{retention?.jobs.length} completed jobs and {retention?.notices.length} read notices are eligible.</p><div className="dialog-actions"><Button variant="outline" onClick={()=>setRetention(null)}>Keep history</Button><Button variant="danger" disabled={!!busy||(!retention?.jobs.length&&!retention?.notices.length)} onClick={applyRetention}>Remove reviewed metadata</Button></div></Dialog>
 </section>;
}
