
CREATE TABLE IF NOT EXISTS schema_version(version INTEGER PRIMARY KEY);
INSERT OR IGNORE INTO schema_version VALUES(1);
CREATE TABLE IF NOT EXISTS runs(id TEXT PRIMARY KEY, target_id TEXT NOT NULL, started_at TEXT NOT NULL,
 label TEXT NOT NULL, status TEXT NOT NULL, profile_json TEXT NOT NULL, payload_json TEXT NOT NULL,
 artifact_hash TEXT NOT NULL);
CREATE TABLE IF NOT EXISTS evidence(id TEXT PRIMARY KEY, run_id TEXT NOT NULL REFERENCES runs(id) ON DELETE CASCADE,
 kind TEXT NOT NULL, state TEXT NOT NULL, payload_json TEXT NOT NULL);
CREATE INDEX IF NOT EXISTS evidence_run ON evidence(run_id);
CREATE TABLE IF NOT EXISTS steps(run_id TEXT NOT NULL REFERENCES runs(id) ON DELETE CASCADE,
 step_id TEXT NOT NULL,payload_json TEXT NOT NULL,PRIMARY KEY(run_id,step_id));
CREATE TABLE IF NOT EXISTS frames(run_id TEXT NOT NULL REFERENCES runs(id) ON DELETE CASCADE,
 frame_id TEXT NOT NULL,payload_json TEXT NOT NULL,PRIMARY KEY(run_id,frame_id));
CREATE TABLE IF NOT EXISTS cookies(run_id TEXT NOT NULL REFERENCES runs(id) ON DELETE CASCADE,
 ordinal INTEGER NOT NULL,payload_json TEXT NOT NULL,PRIMARY KEY(run_id,ordinal));
CREATE TABLE IF NOT EXISTS baselines(target_id TEXT PRIMARY KEY,run_id TEXT NOT NULL REFERENCES runs(id),
 reason TEXT NOT NULL,selected_at TEXT NOT NULL);
CREATE TABLE IF NOT EXISTS audit(id TEXT PRIMARY KEY,at TEXT NOT NULL,action TEXT NOT NULL,
 subject TEXT NOT NULL,reason TEXT NOT NULL);
