import {useState} from 'react';
import {ArrowRight,ArrowUpRight,Check,GitCompareArrows,Search,SlidersHorizontal} from 'lucide-react';
import {request,useResource} from '../api/client';
import type {Run,RunPage} from '../api/types';
import {Dialog,Notice,PageTitle,ResourceState,RunSelect,Status} from '../components/common';
import {Button} from '../components/ui/button';
import Monitoring from '../components/Monitoring';

export default function Assessments({search='',navigate}:{search?:string;navigate:(path:string)=>void}){
 const params=new URLSearchParams(search),activeQuery=params.get('q')||'',offset=Math.min(10000,Math.max(0,Number(params.get('offset'))||0));
 const view=params.get('view')==='monitoring'?'monitoring':params.get('view')==='inbox'?'inbox':'records';
 const selected=(params.get('pair')||'').split(',').filter(x=>/^[a-f0-9]{32}$/.test(x)).slice(0,2);
 const [query,setQuery]=useState(activeQuery),[pairOpen,setPairOpen]=useState(false),[draftPair,setDraftPair]=useState(['','']);
 const [baseline,setBaseline]=useState<Run|null>(null),[reason,setReason]=useState(''),[error,setError]=useState(''),[saving,setSaving]=useState(false),[confirming,setConfirming]=useState(false),[feedback,setFeedback]=useState('');
 const r=useResource<RunPage>(view==='records'?'/api/v1/runs?limit=50&offset='+offset+'&q='+encodeURIComponent(activeQuery):null);
 function update(values:Record<string,string>){const p=new URLSearchParams(search);for(const [k,v]of Object.entries(values))v?p.set(k,v):p.delete(k);navigate('/assessments?'+p.toString());}
 function toggle(id:string){const next=selected.includes(id)?selected.filter(x=>x!==id):selected.length<2?[...selected,id]:[selected[1],id];update({pair:next.join(',')});}
 function role(id:string){return selected[0]===id?'Baseline selected':selected[1]===id?'Candidate selected':'Available for review';}
 async function save(){if(!baseline)return;setSaving(true);setError('');try{await request('/api/v1/baselines',undefined,{run_id:baseline.id,reason});setFeedback('Saved baseline: '+baseline.label+'. This is a comparison reference.');setBaseline(null);setReason('');setConfirming(false);r.retry();}catch(e){setError((e as Error).message);}finally{setSaving(false);}}
 return <><PageTitle eyebrow="01 / Local evidence" title="Your review workspace." description="Recorded journeys, with their context attached."/>
 <div className="workspace-tabs" role="group" aria-label="Assessment workspace">{[['records','Recorded visits'],['monitoring','Monitoring'],['inbox','Inbox']].map(([key,label])=><Button key={key} variant={view===key?'default':'ghost'} aria-pressed={view===key} onClick={()=>update({view:key==='records'?'':key})}>{label}</Button>)}</div>
 {view!=='records'?<Monitoring view={view} navigate={navigate}/>:<>
 <form className="list-toolbar" onSubmit={e=>{e.preventDefault();update({q:query,offset:''});}}><label className="field"><span>Find a run or target</span><input type="search" maxLength={200} value={query} onChange={e=>setQuery(e.target.value)} placeholder="Search local records"/><small>Labels, targets or opaque run IDs</small></label><Button type="submit"><Search size={18}/>Search</Button>{activeQuery&&<Button type="button" variant="outline" onClick={()=>{setQuery('');update({q:'',offset:''});}}>Clear filters</Button>}</form>
 <section className="pair-band" aria-label="Temporary comparison pair"><div><strong>{selected.length?selected.map((id,i)=>(i===0?'Baseline ':'Candidate ')+id.slice(0,8)).join(' → '):'Choose the visits you want to compare.'}</strong><p>Temporary roles do not replace a saved baseline.</p></div><div className="button-group"><Button variant="ghost" onClick={()=>{setDraftPair([selected[0]||'',selected[1]||'']);setPairOpen(true);}}><SlidersHorizontal size={16}/>Change pair</Button><Button disabled={selected.length!==2||selected[0]===selected[1]} onClick={()=>navigate('/changes?baseline='+selected[0]+'&candidate='+selected[1])}><GitCompareArrows size={16}/>Compare selected</Button></div></section>
 {feedback&&<p className="feedback" role="status"><Check size={16}/>{feedback}</p>}
 <div className="section-heading"><div><h2>Recorded assessments</h2><p className="muted">{r.data?r.data.total+' local records · newest first':'Local evidence list'}</p></div><Button variant="outline" disabled={!selected[0]||!!r.data?.demo} onClick={async()=>{setError('');setConfirming(false);setReason('');try{const result=await request<{run:Run}>('/api/v1/runs/'+selected[0]);setBaseline(result.run);}catch(e){setFeedback((e as Error).message);}}}><Check size={16}/>Select saved baseline</Button></div>
 <ResourceState {...r} empty={!!r.data&&!r.data.total&&!activeQuery}>{r.data&&<>
 {!r.data.total&&activeQuery?<Notice title="No matching records"><p>Clear the filters to see all locally recorded visits.</p></Notice>:<ul className="record-list" aria-label="Recorded checkout visits">{r.data.items.map(run=><li key={run.id} className={selected.includes(run.id)?'is-selected':''}>
 <label className="record-selection"><input type="checkbox" aria-label={'Select '+run.label} checked={selected.includes(run.id)} onChange={()=>toggle(run.id)}/></label>
 <article className="record-card"><div className="record-identity"><button className="record-title" onClick={()=>navigate('/runs/'+run.id+'/journey')}>{run.label}</button><time dateTime={run.started_at}>{new Date(run.started_at).toISOString().replace('T',' ').slice(0,19)} UTC</time><code>{run.id.slice(0,12)}</code></div><div className="record-context"><span>{run.profile.mode} · {run.profile.consent} · {run.provenance.replaceAll('_',' ')}</span><Status value={run.status}/><small>{run.complete_states.join(' → ')||'No complete observed window'}</small></div><div className="record-role"><span>{role(run.id)}</span>{run.is_baseline&&<strong>Saved baseline · comparison reference</strong>}</div><Button variant="ghost" aria-label={'Open journey '+run.label} onClick={()=>navigate('/runs/'+run.id+'/journey')}><ArrowUpRight size={18}/></Button></article></li>)}</ul>}
 <div className="pagination"><span>{r.data.total?offset+1:0}–{Math.min(offset+50,r.data.total)} of {r.data.total} records · {selected.length} selected</span><div><Button variant="outline" disabled={offset===0} onClick={()=>update({offset:String(Math.max(0,offset-50))})}>Previous</Button><Button variant="outline" disabled={offset+50>=r.data.total} onClick={()=>update({offset:String(offset+50)})}>Next<ArrowRight size={15}/></Button></div></div>{r.data.demo&&<p className="muted">Baseline selection is unavailable in the read-only synthetic demo.</p>}
 </>}</ResourceState><Notice title="Keep the evidence boundary visible" tone="info"><p>Missing observations remain unknown. A new script or a recorded change is a starting point for review.</p></Notice></>}
 <Dialog open={pairOpen} onClose={()=>setPairOpen(false)} title="Choose comparison roles"><div className="form-grid"><RunSelect label="Baseline" value={draftPair[0]} onChange={v=>setDraftPair([v,draftPair[1]])} runs={r.data?.items||[]}/><RunSelect label="Candidate" value={draftPair[1]} onChange={v=>setDraftPair([draftPair[0],v])} runs={r.data?.items||[]}/></div>{draftPair[0]&&draftPair[0]===draftPair[1]&&<p role="alert" className="error-text">Choose two different records.</p>}<p className="muted">Choices follow the current records page and filter. Selected IDs stay attached.</p><div className="dialog-actions"><Button variant="outline" onClick={()=>setDraftPair([draftPair[1],draftPair[0]])}>Swap roles</Button><Button variant="ghost" onClick={()=>{update({pair:''});setPairOpen(false);}}>Clear pair</Button><Button disabled={!draftPair[0]||!draftPair[1]||draftPair[0]===draftPair[1]} onClick={()=>{update({pair:draftPair.join(',')});setPairOpen(false);}}>Use this pair</Button></div></Dialog>
 <Dialog open={!!baseline} onClose={()=>{if(!saving)setBaseline(null);}} title={confirming?'Confirm saved baseline':'Select a saved baseline'}><p>{baseline?.label}</p><p>This records a comparison reference. It does not certify the run as safe or approve its scripts.</p>{confirming?<div className="surface"><span className="eyebrow">Your selection reason</span><p>{reason}</p><code>{baseline?.id}</code></div>:<label className="field"><span>Selection reason</span><textarea autoFocus minLength={3} maxLength={500} value={reason} onChange={e=>setReason(e.target.value)}/></label>}{error&&<p role="alert" className="error-text">{error}</p>}<div className="dialog-actions"><Button variant="outline" disabled={saving} onClick={()=>confirming?setConfirming(false):setBaseline(null)}>{confirming?'Edit reason':'Cancel'}</Button><Button disabled={reason.trim().length<3||saving} onClick={()=>confirming?void save():setConfirming(true)}>{saving?'Saving…':confirming?'Confirm baseline':'Review selection'}</Button></div></Dialog></>;
}
