import {useState} from 'react';
import {ArrowRight,FolderOpen} from 'lucide-react';
import {request,useResource} from '../api/client';
import type {Run,RunPage} from '../api/types';
import {Dialog,Notice,PageTitle,ResourceState,Status} from '../components/common';
import {Button} from '../components/ui/button';

export default function Assessments({navigate}:{navigate:(path:string)=>void}){
 const [query,setQuery]=useState(''),[activeQuery,setActiveQuery]=useState(''),[offset,setOffset]=useState(0),[selected,setSelected]=useState<string[]>([]);
 const [baseline,setBaseline]=useState<Run|null>(null),[reason,setReason]=useState(''),[error,setError]=useState(''),[saving,setSaving]=useState(false);
 const r=useResource<RunPage>('/api/v1/runs?limit=50&offset='+offset+'&q='+encodeURIComponent(activeQuery));
 function toggle(id:string){setSelected(s=>s.includes(id)?s.filter(x=>x!==id):s.length<2?[...s,id]:[s[1],id]);}
 async function save(){if(!baseline)return;setSaving(true);setError('');try{await request('/api/v1/baselines',undefined,{run_id:baseline.id,reason});setBaseline(null);setReason('');r.retry();}catch(e){setError((e as Error).message);}finally{setSaving(false);}}
 return <><PageTitle eyebrow="01 / Recorded visits" title="Assessments" description="Start with a recorded journey. Keep its context attached."/>
 <form className="list-toolbar" onSubmit={e=>{e.preventDefault();setActiveQuery(query);setOffset(0);}}><label className="field"><span>Find a run or target</span><input type="search" maxLength={200} value={query} onChange={e=>setQuery(e.target.value)} placeholder="Search local records"/></label><Button type="submit" variant="outline">Filter records</Button>{activeQuery&&<Button type="button" variant="ghost" onClick={()=>{setQuery('');setActiveQuery('');setOffset(0);}}>Clear filters</Button>}<Button type="button" disabled={selected.length!==2} onClick={()=>navigate('/changes?baseline='+selected[0]+'&candidate='+selected[1])}>Compare selected <ArrowRight size={16}/></Button></form>
 <ResourceState {...r} empty={!!r.data&&!r.data.total&&!activeQuery}>{r.data&&<>
 {!r.data.total&&activeQuery?<Notice title="No matching records"><p>Clear the filters to see all locally recorded visits.</p></Notice>:<div className="table-scroll"><table><caption className="sr-only">Recorded checkout visits. Select two runs to compare.</caption><thead><tr><th scope="col">Select</th><th scope="col">Recorded journey</th><th scope="col">Coverage</th><th scope="col">Context</th><th scope="col">Review</th></tr></thead><tbody>{r.data.items.map(run=><tr key={run.id}><td><input type="checkbox" aria-label={'Select '+run.label} checked={selected.includes(run.id)} onChange={()=>toggle(run.id)}/></td><td><button className="text-link" onClick={()=>navigate('/runs/'+run.id+'/journey')}>{run.label}</button><time className="row-meta" dateTime={run.started_at}>{new Date(run.started_at).toISOString().replace('T',' ').slice(0,19)} UTC</time><code className="run-id">{run.id.slice(0,12)}</code>{run.is_baseline&&<span className="baseline-label">Selected baseline</span>}</td><td><Status value={run.status}/><span className="row-meta">{run.complete_states.join(' → ')||'No complete observed window'}</span></td><td><span>{run.profile.mode} · {run.profile.consent}</span><span className="row-meta">{run.provenance.replaceAll('_',' ')}</span></td><td><Button variant="ghost" onClick={()=>navigate('/runs/'+run.id+'/journey')}><FolderOpen size={15}/>Journey</Button><Button variant="ghost" disabled={r.data?.demo} onClick={()=>{setBaseline(run);setReason('');setError('');}}>Select baseline</Button></td></tr>)}</tbody></table></div>}
 <div className="pagination"><span>{r.data.total} local records · {selected.length} selected</span><div><Button variant="outline" disabled={offset===0} onClick={()=>setOffset(x=>Math.max(0,x-50))}>Previous</Button><Button variant="outline" disabled={offset+50>=r.data.total} onClick={()=>setOffset(x=>x+50)}>Next</Button></div></div>{r.data.demo&&<p className="muted">Baseline selection is unavailable in the read-only synthetic demo.</p>}
 </>}</ResourceState>
 <Dialog open={!!baseline} onClose={()=>setBaseline(null)} title="Select a baseline"><p>{baseline?.label}</p><p>This records a comparison reference. It does not certify the run as safe or approve its scripts.</p><label className="field"><span>Selection reason</span><textarea autoFocus minLength={3} maxLength={500} value={reason} onChange={e=>setReason(e.target.value)}/></label>{error&&<p role="alert">{error}</p>}<div className="dialog-actions"><Button variant="outline" onClick={()=>setBaseline(null)}>Cancel</Button><Button disabled={reason.trim().length<3||saving} onClick={save}>{saving?'Saving…':'Confirm baseline'}</Button></div></Dialog>
 </>;
}
