import {useEffect} from 'react';
import {useResource} from '../api/client';
import type {Comparison,RunPage,EvidenceDetail,Change} from '../api/types';
import {Notice,PageTitle,ResourceState,RunSelect,Status,FindingList,ExportControl} from '../components/common';
import {Button} from '../components/ui/button';
import {ArrowLeft,ArrowRight,ArrowUpRight,FileCode2} from 'lucide-react';
import ReviewPanel from '../components/ReviewPanel';

function ComparisonEvidence({change,back,navigate}:{change:Change|undefined;back:string;navigate:(path:string)=>void}){
 const a=useResource<EvidenceDetail>(change?.baseline_evidence_id?'/api/v1/evidence/'+change.baseline_evidence_id:null);
 const b=useResource<EvidenceDetail>(change?.candidate_evidence_id?'/api/v1/evidence/'+change.candidate_evidence_id:null);
 if(!change)return <div className="evidence-empty"><FileCode2 size={30}/><span className="eyebrow">Follow the evidence</span><h2>Select a change</h2><p>Its originating state, before/after representation and limitations will appear here.</p></div>;
 return <section className="comparison-evidence"><h2 className="resource-heading">{change.url_display||'Cookie attributes'}</h2><p className="muted">{change.kind.replaceAll('_',' ')} · {change.state}</p><Notice title={change.reason.replaceAll('_',' ')} tone="info"><p>A difference identifies an observation to review. It does not establish maliciousness.</p></Notice>
 <div className="evidence-pair">{[{name:'Baseline',resource:a,id:change.baseline_evidence_id},{name:'Candidate',resource:b,id:change.candidate_evidence_id}].map(({name,resource,id})=><article key={name}><span className="eyebrow">{name}</span>{!id?<p className="muted">{change.category==='COOKIE'?'Attribute-level comparison. Cookie values are never retained.':'No linked evidence record for this side.'}</p>:<ResourceState {...resource}>{resource.data&&<><h3>{resource.data.record.body_size===null?'Body unavailable':resource.data.record.body_size.toLocaleString()+' bytes'}</h3><code>{resource.data.record.body_sha256||resource.data.record.body_reason||'No retained body hash'}</code><small>{resource.data.record.body_representation||'Representation unavailable'}</small><Status value={resource.data.integrity.state}/></>}</ResourceState>}</article>)}</div>
 {(a.data||b.data)&&<div className="surface"><h3>Observation layers</h3>{[a,b].map((r,i)=>r.data&&<p className="mono" key={i}>{i?'Candidate':'Baseline'} · Reference: {r.data.record.reference_observed?'observed':'not observed'} · Request: {r.data.record.request_observed?'observed':'not observed'} · Response: {r.data.record.http_status||'not observed'} · Execution: not measured</p>)}</div>}
 <div className="button-group">{change.candidate_evidence_id&&<Button onClick={()=>navigate('/evidence/'+change.candidate_evidence_id+'?back='+encodeURIComponent(back))}>Open candidate evidence<ArrowUpRight size={16}/></Button>}{change.baseline_evidence_id&&<Button variant="outline" onClick={()=>navigate('/evidence/'+change.baseline_evidence_id+'?back='+encodeURIComponent(back))}><ArrowLeft size={16}/>Open baseline evidence</Button>}</div>
 {change.category==='COOKIE'&&<p className="muted">Review the owning run's exported cookie attribute metadata for the before/after details.</p>}
 </section>;
}

export default function Changes({search,navigate}:{search:string;navigate:(path:string)=>void}){
 const params=new URLSearchParams(search),baseline=params.get('baseline')||'',candidate=params.get('candidate')||'',selected=params.get('selected')||'',filter=params.get('filter')||'ALL';
 const runs=useResource<RunPage>('/api/v1/runs?limit=100');
 const valid=!!baseline&&!!candidate&&baseline!==candidate;
 const result=useResource<Comparison>(valid?'/api/v1/comparisons?baseline='+baseline+'&candidate='+candidate:null);
 useEffect(()=>{if(selected&&result.data){const timer=requestAnimationFrame(()=>document.querySelector<HTMLElement>('[data-evidence-key="'+CSS.escape(selected)+'"]')?.focus({preventScroll:true}));return()=>cancelAnimationFrame(timer);}},[selected,result.data]);
 function update(values:Record<string,string>){const p=new URLSearchParams(search);for(const[k,v]of Object.entries(values))v?p.set(k,v):p.delete(k);navigate('/changes?'+p.toString());}
 const visible=result.data?.changes.filter(c=>filter==='ALL'||c.kind===filter)||[];
 const selection=visible.find(c=>(c.candidate_evidence_id||c.baseline_evidence_id||c.identity)===selected);
 const back='/changes?'+params.toString();
 return <><PageTitle eyebrow="03 / Local evidence" title="Changes, with receipts." description="Inspect what differs. Keep the observation boundary in view.">{candidate&&<ExportControl id={candidate}/>}</PageTitle>
 <section className="comparison-band"><div className="inline-meta">{result.data&&<Status value={result.data.eligibility}/>}<span>Temporary comparison roles · same profile required</span></div>
 <ResourceState loading={runs.loading} error={runs.error} retry={runs.retry}><div className="comparison-toolbar"><RunSelect label="Baseline" value={baseline} onChange={v=>update({baseline:v,selected:''})} runs={runs.data?.items||[]}/><ArrowRight aria-hidden size={20}/><RunSelect label="Candidate" value={candidate} onChange={v=>update({candidate:v,selected:''})} runs={runs.data?.items||[]}/></div>{runs.data&&runs.data.total>100&&<p className="muted">100 most recent runs shown. Choose older pairs from Assessments.</p>}</ResourceState><p className="muted">Missing visibility remains unknown. A baseline choice is not a security approval.</p></section>
 {!baseline||!candidate?<Notice title="Choose two recorded visits" tone="info"><p>Comparison preserves both recorded observation profiles.</p></Notice>:baseline===candidate?<Notice title="Choose different records"><p>The same visit cannot establish a change over time.</p><Button variant="outline" onClick={()=>update({candidate:'',selected:''})}>Choose another candidate</Button></Notice>:<ResourceState {...result}>{result.data&&(result.data.eligibility==='INCOMPATIBLE_PROFILE'?<Notice title="These visits are not comparable"><p>The following profile fields differ:</p><ul>{result.data.mismatch_fields.map(f=><li key={f}>{f.replaceAll('_',' ')}</li>)}</ul><Button variant="outline" onClick={()=>navigate('/runs/'+candidate+'/journey')}>Review candidate profile</Button></Notice>:<>
 <div className="filter-tabs" role="group" aria-label="Filter changes">{['ALL','ADDED','CHANGED','NOT_OBSERVED','AMBIGUOUS','UNOBSERVABLE'].map(f=><Button key={f} variant={filter===f?'default':'ghost'} aria-pressed={filter===f} onClick={()=>update({filter:f,selected:''})}>{f.replaceAll('_',' ')} · {f==='ALL'?result.data!.changes.length:result.data!.changes.filter(c=>c.kind===f).length}</Button>)}</div>
 <div className="change-layout"><section className="change-list" aria-label="Observed changes">{!visible.length?<div className="state-message"><h2>{filter==='ALL'?'No recorded differences':'No matches for this filter'}</h2><p>Interpret this within the reached states and captured evidence.</p>{filter!=='ALL'&&<Button variant="outline" onClick={()=>update({filter:'ALL'})}>Clear filter</Button>}</div>:visible.map(c=>{const key=c.candidate_evidence_id||c.baseline_evidence_id||c.identity;return <button key={key+c.kind} data-evidence-key={key} className={'change-row '+(selected===key?'selected':'')} onClick={()=>update({selected:key})} aria-pressed={selected===key}><span className="change-row-top"><FileCode2 size={17}/><Status value={c.kind}/></span><strong>{c.url_display||'Cookie attributes'}</strong><span>{c.category} · {c.state}</span><small className="mono">Resource {c.identity.slice(0,12)}</small>{c.new_origin&&<span className="origin-note">New observed origin · ownership unknown</span>}</button>;})}</section><div className="evidence-column"><ComparisonEvidence change={selection} back={back} navigate={navigate}/></div></div>
 <details className="all-findings surface"><summary>Scoped observations and standards context</summary><FindingList findings={result.data.findings}/></details></>)}</ResourceState>}
 {valid&&result.data&&<ReviewPanel key={baseline+candidate} baseline={baseline} candidate={candidate}/>}
 </>;
}
