import {useState} from 'react';
import {ArrowUpRight,Layers} from 'lucide-react';
import {useResource} from '../api/client';
import type {Journey as JourneyData,RunPage} from '../api/types';
import {ExportControl,Notice,PageTitle,ProfileDetails,ResourceState,RunSelect,Status} from '../components/common';
import {Button} from '../components/ui/button';

export default function Journey({id,navigate}:{id:string;navigate:(path:string)=>void}){
 const runList=useResource<RunPage>(!id?'/api/v1/runs?limit=100':null);
 const r=useResource<JourneyData>(id?'/api/v1/runs/'+id+'/journey':null);
 const [step,setStep]=useState('');
 const selected=r.data?.steps.find(s=>s.id===step)||r.data?.steps[0];
 const evidence=r.data?.evidence.filter(e=>e.step_id===selected?.id)||[];
 return <><PageTitle eyebrow="02 / Local evidence" title="Trace the recorded journey." description={id?id:'See where the observer reached, stopped, or lacked visibility.'}>{id&&<ExportControl id={id}/>}</PageTitle>
 {!id?<ResourceState {...runList} empty={!!runList.data&&!runList.data.total}><div className="surface"><RunSelect label="Recorded journey" value="" onChange={v=>navigate('/runs/'+v+'/journey')} runs={runList.data?.items||[]}/></div></ResourceState>:<ResourceState {...r}>{r.data&&<>
 <ProfileDetails profile={r.data.profile}/>{r.data.pilot_context&&<details className="surface"><summary>Retained pilot authorization context</summary><p className="muted">{r.data.pilot_context.notice}</p><dl className="metadata-grid"><div><dt>Approved origins</dt><dd>{r.data.pilot_context.approved_origins.join(', ')}</dd></div><div><dt>Grant window</dt><dd>{r.data.pilot_context.issued_at}<br/>{r.data.pilot_context.expires_at}</dd></div><div><dt>Configuration revision</dt><dd>{r.data.pilot_context.configuration_version}</dd></div><div><dt>Configuration SHA-256</dt><dd>{r.data.pilot_context.configuration_sha256}</dd></div></dl></details>}<div className="inline-meta"><Status value={r.data.provenance}/><span>Complete bounded windows: {r.data.complete_states.join(', ')||'none'}</span></div>
 {r.data.limitation_codes.length>0&&<Notice title="This record has visibility limits"><p>{r.data.limitation_codes.join(' · ')}</p></Notice>}
 {!r.data.steps.length?<Notice title="No declared steps in this record"><p>Imported evidence may have incomplete journey context.</p></Notice>:<div className="journey-layout"><ol className="stage-list" aria-label="Recorded observation steps">{r.data.steps.map((s,i)=><li key={s.id}><button aria-pressed={selected?.id===s.id} className={selected?.id===s.id?'selected':''} onClick={()=>setStep(s.id)}><span className="stage-number">{String(i+1).padStart(2,'0')} / {s.status.replaceAll('_',' ')}</span><strong>{s.state}</strong><time>{s.started_at.slice(11,19)} → {s.ended_at.slice(11,19)} UTC</time></button></li>)}</ol><div className="journey-content"><section className="surface step-detail"><Status value={selected?.status||'UNKNOWN'}/><h2>{selected?.state}</h2><p>{selected?.reason?.replaceAll('_',' ')||'The declared step finished within its bounded observation window. Script execution was not measured.'}</p><dl className="metadata-grid"><div><dt>Started / ended</dt><dd>{selected?.started_at}<br/>{selected?.ended_at}</dd></div><div><dt>Step identifier</dt><dd>{selected?.id}</dd></div></dl>{selected?.status!=='REACHED'&&<Notice title="Dependent checks were not evaluated"><p>Missing coverage cannot establish that a script disappeared or that this state was safe.</p></Notice>}</section>
 <section className="surface"><h2><Layers size={21}/> Frame inventory</h2><p className="muted">Origin, parent and visibility belong to each observation.</p><dl className="metadata-grid">{r.data.frames.map(f=><div key={f.id}><dt>{f.id} · {f.visibility}</dt><dd>{f.origin||'Origin unavailable'}<br/>Parent: {f.parent_id||'top level'}</dd></div>)}</dl>{!r.data.frames.length&&<p className="muted">No frame metadata retained.</p>}</section>
 <section className="surface"><h2>Evidence from this step</h2>{evidence.length?<ul className="evidence-links">{evidence.map(e=><li key={e.id}><span className="eyebrow">{e.kind} · {e.frame_id}</span><strong>{e.url_display||'Inline metadata only'}</strong><Button variant="outline" onClick={()=>navigate('/evidence/'+e.id)}>View evidence<ArrowUpRight size={15}/></Button></li>)}</ul>:<p className="muted">No evidence linked to this step.</p>}</section></div></div>}
 </>}</ResourceState>}</>;
}
